import React, { FC, PropsWithChildren, Suspense } from 'react';
import type { Metadata } from 'next';
import { VT323 } from 'next/font/google';
import { Footer } from '../components/Footer';
import Loading from './loading';
import './global.css';

const vt323font = VT323({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
});

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Snake Game by ',
  description: 'Generated by create next app',
  authors: { name: 'Sk3ll', url: 'https://github.com/Sk3ll' },
};

const RootLayout: FC<PropsWithChildren> = ({
  children,
}) => (
  <html lang="en" className={vt323font.className}>
    <body>
      <div className="flex flex-col gap-y-[1.5rem]">
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
        <Footer />
      </div>
    </body>
  </html>
);

export default RootLayout;
