import React, { FC, PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import './global.css';

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Snake Game by Sk3ll',
  description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({
  children,
}) => (
  <html lang="en">
    <body>{children}</body>
  </html>
);

export default RootLayout;
